import*as THREE from"three";import{EnemySystem}from"./EnemySystem";import{Player}from"./Player";import{SpellSystem}from"./SpellSystem";import{World}from"./World";import{loadProgress,loadSettings,saveProgress,saveSettings}from"./Save";import type{Progress,Settings}from"./types";
export interface UpgradeChoice{title:string;text:string;apply:(g:Game)=>void}
export class Game{
readonly renderer:THREE.WebGLRenderer;readonly scene=new THREE.Scene();readonly camera:THREE.PerspectiveCamera;readonly player:Player;readonly world:World;readonly enemies:EnemySystem;readonly spells:SpellSystem;settings:Settings=loadSettings();progress:Progress=loadProgress();running=false;score=0;indirect=0;district=1;elapsed=0;onHud?:()=>void;onUpgrade?:(c:UpgradeChoice[])=>void;onDeath?:()=>void;private last=performance.now();private grabbed:ReturnType<World["nearest"]>=null;private waveTransition=false;
constructor(container:HTMLElement){this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});this.renderer.setPixelRatio(this.settings.quality==="high"?Math.min(devicePixelRatio,1.6):1);this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=this.settings.quality!=="low";this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.15;container.appendChild(this.renderer.domElement);this.camera=new THREE.PerspectiveCamera(this.settings.fov,innerWidth/innerHeight,.08,350);this.player=new Player(this.camera,this.settings);this.world=new World(this.scene);this.enemies=new EnemySystem(this.scene,this.player,(e,ind)=>{this.score+=e.type==="boss"?2500:e.type==="spectre"?350:e.type==="kamikaze"?260:200;if(ind){this.indirect++;this.score+=300}});this.spells=new SpellSystem(this.scene,this.player,this.world,this.enemies);this.scene.fog=new THREE.FogExp2(0x0b0812,.014);this.scene.background=new THREE.Color(0x090711);addEventListener("resize",()=>this.resize());document.addEventListener("keydown",e=>this.key(e,true));document.addEventListener("keyup",e=>this.key(e,false));document.addEventListener("mousemove",e=>{if(document.pointerLockElement===this.renderer.domElement)this.player.onMouse(e.movementX,e.movementY)});document.addEventListener("mousedown",e=>{if(this.running&&document.pointerLockElement===this.renderer.domElement&&e.button===0)this.spells.cast(this.elapsed)});document.addEventListener("mouseup",e=>{if(e.button===0&&this.grabbed)this.throwGrabbed()})}
start(){this.running=true;this.renderer.domElement.requestPointerLock();this.last=performance.now()}
restart(){this.score=0;this.indirect=0;this.elapsed=0;this.district=1;this.player.hp=this.player.maxHp;this.player.position.set(0,1.75,15);this.player.velocity.set(0,0,0);this.enemies.reset();this.spells.damageMultiplier=1;this.spells.radiusMultiplier=1;this.spells.cooldownMultiplier=1;this.running=true;this.waveTransition=false;this.renderer.domElement.requestPointerLock()}
setSettings(s:Settings){this.settings=s;saveSettings(s);this.player.setSettings(s);this.renderer.setPixelRatio(s.quality==="high"?Math.min(devicePixelRatio,1.6):1);this.renderer.shadowMap.enabled=s.quality!=="low";this.resize()}
chooseUpgrade(c:UpgradeChoice){c.apply(this);this.waveTransition=false;this.enemies.beginWave(this.enemies.wave+1);this.running=true;this.renderer.domElement.requestPointerLock()}
loop=(now:number)=>{requestAnimationFrame(this.loop);const dt=Math.min((now-this.last)/1000,.05);this.last=now;if(this.running){this.elapsed+=dt;this.player.update(dt);this.world.update(dt);this.enemies.update(dt,this.elapsed);this.spells.update(dt,this.elapsed);this.updateGrab();if(this.enemies.cleared()&&!this.waveTransition){if(this.enemies.wave<3)this.openUpgrade();else this.nextDistrict()}if(this.player.hp<=0)this.die()}this.onHud?.();this.renderer.render(this.scene,this.camera)}
private key(e:KeyboardEvent,d:boolean){this.player.onKey(e.code,d);if(!d||!this.running)return;if(e.code==="Space")this.player.jump();if(e.code==="ShiftLeft"||e.code==="ShiftRight")this.player.dash();if(e.code==="KeyF")this.toggleGrab();if(/Digit[1-6]/.test(e.code))this.spells.select(Number(e.code.at(-1))-1)}
private toggleGrab(){if(this.grabbed){this.throwGrabbed();return}const d=this.world.nearest(this.camera.position,this.player.forward(),18);if(!d)return;this.grabbed=d;d.grabbed=true;d.velocity.set(0,0,0)}
private updateGrab(){if(!this.grabbed)return;this.grabbed.mesh.position.lerp(this.camera.position.clone().addScaledVector(this.player.forward(),4.2),.28);this.grabbed.mesh.rotation.y+=.03}
private throwGrabbed(){if(!this.grabbed)return;this.grabbed.grabbed=false;this.grabbed.velocity.copy(this.player.forward()).multiplyScalar(28);this.grabbed=null}
private openUpgrade(){this.waveTransition=true;this.running=false;document.exitPointerLock();this.onUpgrade?.(this.choices())}
private nextDistrict(){this.score+=5000;this.district++;this.player.heal(35);this.enemies.beginWave(1)}
private die(){this.running=false;document.exitPointerLock();this.progress.runs++;this.progress.bestScore=Math.max(this.progress.bestScore,this.score);saveProgress(this.progress);this.onDeath?.()}
private resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)}
private choices():UpgradeChoice[]{const p:UpgradeChoice[]=[{title:"Résonance",text:"+25% dégâts de sorts",apply:g=>g.spells.damageMultiplier*=1.25},{title:"Anomalie",text:"+30% rayon des explosions",apply:g=>g.spells.radiusMultiplier*=1.3},{title:"Flux rapide",text:"-18% temps de recharge",apply:g=>g.spells.cooldownMultiplier*=.82},{title:"Pas spectral",text:"+18% vitesse",apply:g=>g.player.moveSpeed*=1.18},{title:"Déchaînement",text:"Dash plus violent",apply:g=>g.player.dashPower*=1.25},{title:"Sang arcanique",text:"+25 PV max",apply:g=>{g.player.maxHp+=25;g.player.hp=g.player.maxHp}}];return p.sort(()=>Math.random()-.5).slice(0,3)}
}
