import*as THREE from"three";import type{EnemySystem}from"./EnemySystem";import type{Player}from"./Player";import type{World}from"./World";import type{SpellDefinition,SpellId}from"./types";
export class SpellSystem{
readonly spells:SpellDefinition[]=[{id:"impact",name:"Impact",cooldown:.32,color:0xb793ff,damage:34},{id:"braise",name:"Braise",cooldown:.65,color:0xff6b42,damage:48},{id:"givre",name:"Givre",cooldown:.75,color:0x73d9ff,damage:24},{id:"faille",name:"Faille",cooldown:1.6,color:0xcc54ff,damage:55},{id:"arc",name:"Arc",cooldown:.95,color:0xffe66e,damage:40},{id:"nova",name:"Nova",cooldown:3.2,color:0xff55aa,damage:62}];selected=0;cooldowns=new Map<SpellId,number>();damageMultiplier=1;radiusMultiplier=1;cooldownMultiplier=1;comboText="";private ray=new THREE.Raycaster();private comboUntil=0;
constructor(private scene:THREE.Scene,private player:Player,private world:World,private enemies:EnemySystem){}
update(dt:number,t:number){for(const s of this.spells)this.cooldowns.set(s.id,Math.max(0,(this.cooldowns.get(s.id)??0)-dt));if(t>this.comboUntil)this.comboText=""}
select(i:number){if(i>=0&&i<this.spells.length)this.selected=i}
cast(t:number){const s=this.spells[this.selected];if((this.cooldowns.get(s.id)??0)>0)return;this.cooldowns.set(s.id,s.cooldown*this.cooldownMultiplier);const o=this.player.camera.position.clone(),dir=this.player.forward();this.ray.set(o,dir);const hit=this.ray.intersectObjects([...this.enemies.rayTargets(),...this.world.raycastTargets],false)[0],p=hit?.point??o.clone().addScaledVector(dir,18);if(s.id==="impact")this.impact(hit?.object,dir,s,t);else if(s.id==="braise"){this.enemies.radius(p,3.3*this.radiusMultiplier,s.damage*this.damageMultiplier,6);this.world.explode(p,3,5)}else if(s.id==="givre"){const e=hit?this.enemies.fromObject(hit.object):undefined;if(e){this.enemies.damage(e,s.damage*this.damageMultiplier);this.enemies.freeze(e,t,2.6)}}else if(s.id==="faille"){this.enemies.radius(p,5.2*this.radiusMultiplier,s.damage*this.damageMultiplier,11);this.world.explode(p,5.2*this.radiusMultiplier,8)}else if(s.id==="arc"){const e=hit?this.enemies.fromObject(hit.object):undefined;if(e){this.enemies.damage(e,s.damage*this.damageMultiplier);for(const x of this.enemies.enemies.filter(x=>x!==e).slice(0,3))if(x.mesh.position.distanceTo(e.mesh.position)<8)this.enemies.damage(x,s.damage*.65*this.damageMultiplier)}}else{this.enemies.radius(this.player.position,9*this.radiusMultiplier,s.damage*this.damageMultiplier,20);this.world.explode(this.player.position,9,18)}this.flash(o.clone().addScaledVector(dir,1.2),s.color)}
private impact(obj:THREE.Object3D|undefined,dir:THREE.Vector3,s:SpellDefinition,t:number){if(!obj)return;const e=this.enemies.fromObject(obj);if(e){const frozen=t<e.frozenUntil;this.enemies.damage(e,s.damage*this.damageMultiplier*(frozen?2.25:1),dir.clone().multiplyScalar(frozen?16:9));if(frozen)this.combo("FRACTURE GLACIALE",t);return}const d=obj.userData.destructible;if(d){const destroyed=this.world.damage(d,65*this.damageMultiplier,dir.clone().multiplyScalar(16));if(destroyed&&d.explosive)this.combo("COLLATÉRAL",t);return}if(obj.userData.fragile){this.scene.remove(obj);this.combo("BRÈCHE",t)}if(obj.userData.crystal){this.scene.remove(obj);this.enemies.radius(obj.position,6*this.radiusMultiplier,85*this.damageMultiplier,12,true);this.combo("PLUIE DE CRISTAL",t)}}
private combo(s:string,t:number){this.comboText=s;this.comboUntil=t+1.35}
private flash(p:THREE.Vector3,c:number){const m=new THREE.Mesh(new THREE.SphereGeometry(.2,8,8),new THREE.MeshBasicMaterial({color:c}));m.position.copy(p);this.scene.add(m);setTimeout(()=>this.scene.remove(m),90)}
}
