import*as THREE from"three";import type{Destructible}from"./types";
export class World{
readonly destructibles:Destructible[]=[];readonly raycastTargets:THREE.Object3D[]=[];
constructor(private scene:THREE.Scene){this.build()}
update(dt:number){for(const d of this.destructibles){if(d.grabbed)continue;if(d.velocity.lengthSq()>.0001){d.velocity.y-=16*dt;d.mesh.position.addScaledVector(d.velocity,dt);d.mesh.rotation.x+=d.velocity.z*dt*.05;d.mesh.rotation.z-=d.velocity.x*dt*.05;if(d.mesh.position.y<.7){d.mesh.position.y=.7;d.velocity.y*=-.25;d.velocity.x*=.9;d.velocity.z*=.9}}}}
damage(d:Destructible,a:number,imp?:THREE.Vector3){d.hp-=a;if(imp)d.velocity.add(imp);if(d.hp>0)return false;this.destroy(d);return true}
explode(c:THREE.Vector3,r:number,f:number){for(const d of[...this.destructibles]){const v=d.mesh.position.clone().sub(c),dist=v.length();if(dist>r)continue;const t=1-dist/r;d.velocity.add(v.normalize().multiplyScalar(f*t));d.hp-=65*t;if(d.hp<=0)this.destroy(d)}}
nearest(o:THREE.Vector3,dir:THREE.Vector3,max=18){let best:Destructible|null=null,score=999;for(const d of this.destructibles){const v=d.mesh.position.clone().sub(o),dist=v.length();if(dist>max)continue;const a=1-v.normalize().dot(dir),s=a*9+dist*.03;if(s<score&&a<.16){score=s;best=d}}return best}
private build(){this.scene.add(new THREE.HemisphereLight(0x9f84ff,0x170d20,2.3));const sun=new THREE.DirectionalLight(0xffc2e0,4);sun.position.set(15,35,12);sun.castShadow=true;this.scene.add(sun);const floor=new THREE.Mesh(new THREE.CylinderGeometry(44,44,.7,32),new THREE.MeshToonMaterial({color:0x15121f}));floor.position.y=-.35;this.scene.add(floor);const ring=new THREE.Mesh(new THREE.TorusGeometry(38,.18,6,64),new THREE.MeshBasicMaterial({color:0x8c5bff}));ring.rotation.x=Math.PI/2;ring.position.y=.05;this.scene.add(ring);this.platform(19,5,-20,18,10,10);this.platform(-23,3,-18,14,6,14);this.platform(0,7.5,-34,15,1,6);for(let i=0;i<24;i++){const a=i/24*Math.PI*2,r=22+(i%4)*4;this.crate(Math.cos(a)*r,.8,Math.sin(a)*r,i%5===0)}for(let i=0;i<10;i++){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.8+Math.random()*.5),new THREE.MeshToonMaterial({color:i%2?0xff5a9f:0x9e7cff,emissive:0x251042}));m.position.set(-30+i*6,8+(i%3)*2,-4-(i%4)*6);m.userData.crystal=true;this.scene.add(m);this.raycastTargets.push(m)}for(let i=0;i<12;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(4,4,.55),new THREE.MeshToonMaterial({color:0x211a31}));const a=i/12*Math.PI*2;m.position.set(Math.cos(a)*32,2,Math.sin(a)*32);m.rotation.y=-a;m.userData.fragile=true;this.scene.add(m);this.raycastTargets.push(m)}}
private platform(x:number,y:number,z:number,w:number,h:number,d:number){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshToonMaterial({color:0x7561a8}));m.position.set(x,y-h/2,z);this.scene.add(m)}
private crate(x:number,y:number,z:number,explosive:boolean){const m=new THREE.Mesh(explosive?new THREE.CylinderGeometry(.6,.6,1.4,10):new THREE.BoxGeometry(1.3,1.3,1.3),new THREE.MeshToonMaterial({color:explosive?0xff4f9d:0x8a6a50}));m.position.set(x,y,z);this.scene.add(m);const d:Destructible={mesh:m,hp:explosive?35:55,explosive,velocity:new THREE.Vector3(),grabbed:false};m.userData.destructible=d;this.destructibles.push(d);this.raycastTargets.push(m)}
private destroy(d:Destructible){const i=this.destructibles.indexOf(d);if(i>=0)this.destructibles.splice(i,1);const r=this.raycastTargets.indexOf(d.mesh);if(r>=0)this.raycastTargets.splice(r,1);if(d.explosive)this.explode(d.mesh.position.clone(),6,18);this.scene.remove(d.mesh)}
}
